[package]
name = "leet-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "gRPC service exposing leet-core over network"
keywords.workspace = true
categories.workspace = true
documentation = "https://docs.rs/leet-service"
readme = "README.md"

[dependencies]
leet-core = { path = "../leet-core", version = "1.0.0" }
leet-bridge = { path = "../leet-bridge", version = "1.0.0" }
tonic = "0.11"
prost = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync", "time", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
uuid = { version = "1", features = ["v4"] }
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
parking_lot = "0.12"
rusqlite = { version = "0.31", features = ["bundled"] }
futures-core = "0.3"
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }

[[bin]]
name = "leet-server"
path = "src/bin/leet-server.rs"

[[bin]]
name = "leet-agent"
path = "src/bin/leet-agent.rs"

[build-dependencies]
tonic-build = "0.11"
