# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: leet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'leet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nleet.proto\x12\x04leet\"C\n\rEncodeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"a\n\x0e\x45ncodeResponse\x12\x10\n\x08\x63ogon_id\x18\x01 \x01(\t\x12\x0b\n\x03sem\x18\x02 \x03(\x02\x12\x0b\n\x03unc\x18\x03 \x03(\x02\x12\r\n\x05stamp\x18\x04 \x01(\x03\x12\x14\n\x0ctokens_saved\x18\x05 \x01(\x03\"7\n\rDecodeRequest\x12\x0b\n\x03sem\x18\x01 \x03(\x02\x12\x0b\n\x03unc\x18\x02 \x03(\x02\x12\x0c\n\x04lang\x18\x03 \x01(\t\"\x1e\n\x0e\x44\x65\x63odeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"2\n\x0c\x44\x65ltaRequest\x12\x10\n\x08sem_prev\x18\x01 \x03(\x02\x12\x10\n\x08sem_curr\x18\x02 \x03(\x02\"1\n\rDeltaResponse\x12\r\n\x05patch\x18\x01 \x03(\x02\x12\x11\n\tmagnitude\x18\x02 \x01(\x02\"F\n\rRecallRequest\x12\x0b\n\x03sem\x18\x01 \x03(\x02\x12\x0b\n\x03unc\x18\x02 \x03(\x02\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\t\n\x01k\x18\x04 \x01(\x05\"4\n\x0eRecallResponse\x12\"\n\x07results\x18\x01 \x03(\x0b\x32\x11.leet.CogonRecord\"V\n\x0b\x43ogonRecord\x12\x10\n\x08\x63ogon_id\x18\x01 \x01(\t\x12\x0b\n\x03sem\x18\x02 \x03(\x02\x12\x0b\n\x03unc\x18\x03 \x03(\x02\x12\x0c\n\x04\x64ist\x18\x04 \x01(\x02\x12\r\n\x05stamp\x18\x05 \x01(\x03\"\x0f\n\rHealthRequest\"A\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\x12\x0e\n\x06uptime\x18\x03 \x01(\x03\x32\xd1\x02\n\x0bLeetService\x12\x33\n\x06\x45ncode\x12\x13.leet.EncodeRequest\x1a\x14.leet.EncodeResponse\x12\x33\n\x06\x44\x65\x63ode\x12\x13.leet.DecodeRequest\x1a\x14.leet.DecodeResponse\x12<\n\x0b\x45ncodeBatch\x12\x13.leet.EncodeRequest\x1a\x14.leet.EncodeResponse(\x01\x30\x01\x12\x30\n\x05\x44\x65lta\x12\x12.leet.DeltaRequest\x1a\x13.leet.DeltaResponse\x12\x33\n\x06Recall\x12\x13.leet.RecallRequest\x1a\x14.leet.RecallResponse\x12\x33\n\x06Health\x12\x13.leet.HealthRequest\x1a\x14.leet.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEREQUEST']._serialized_start=20
  _globals['_ENCODEREQUEST']._serialized_end=87
  _globals['_ENCODERESPONSE']._serialized_start=89
  _globals['_ENCODERESPONSE']._serialized_end=186
  _globals['_DECODEREQUEST']._serialized_start=188
  _globals['_DECODEREQUEST']._serialized_end=243
  _globals['_DECODERESPONSE']._serialized_start=245
  _globals['_DECODERESPONSE']._serialized_end=275
  _globals['_DELTAREQUEST']._serialized_start=277
  _globals['_DELTAREQUEST']._serialized_end=327
  _globals['_DELTARESPONSE']._serialized_start=329
  _globals['_DELTARESPONSE']._serialized_end=378
  _globals['_RECALLREQUEST']._serialized_start=380
  _globals['_RECALLREQUEST']._serialized_end=450
  _globals['_RECALLRESPONSE']._serialized_start=452
  _globals['_RECALLRESPONSE']._serialized_end=504
  _globals['_COGONRECORD']._serialized_start=506
  _globals['_COGONRECORD']._serialized_end=592
  _globals['_HEALTHREQUEST']._serialized_start=594
  _globals['_HEALTHREQUEST']._serialized_end=609
  _globals['_HEALTHRESPONSE']._serialized_start=611
  _globals['_HEALTHRESPONSE']._serialized_end=676
  _globals['_LEETSERVICE']._serialized_start=679
  _globals['_LEETSERVICE']._serialized_end=1016
# @@protoc_insertion_point(module_scope)
