# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import leet_pb2 as leet__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in leet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encode = channel.unary_unary(
                '/leet.LeetService/Encode',
                request_serializer=leet__pb2.EncodeRequest.SerializeToString,
                response_deserializer=leet__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.Decode = channel.unary_unary(
                '/leet.LeetService/Decode',
                request_serializer=leet__pb2.DecodeRequest.SerializeToString,
                response_deserializer=leet__pb2.DecodeResponse.FromString,
                _registered_method=True)
        self.EncodeBatch = channel.stream_stream(
                '/leet.LeetService/EncodeBatch',
                request_serializer=leet__pb2.EncodeRequest.SerializeToString,
                response_deserializer=leet__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.Delta = channel.unary_unary(
                '/leet.LeetService/Delta',
                request_serializer=leet__pb2.DeltaRequest.SerializeToString,
                response_deserializer=leet__pb2.DeltaResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/leet.LeetService/Recall',
                request_serializer=leet__pb2.RecallRequest.SerializeToString,
                response_deserializer=leet__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/leet.LeetService/Health',
                request_serializer=leet__pb2.HealthRequest.SerializeToString,
                response_deserializer=leet__pb2.HealthResponse.FromString,
                _registered_method=True)


class LeetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Encode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeBatch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encode': grpc.unary_unary_rpc_method_handler(
                    servicer.Encode,
                    request_deserializer=leet__pb2.EncodeRequest.FromString,
                    response_serializer=leet__pb2.EncodeResponse.SerializeToString,
            ),
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=leet__pb2.DecodeRequest.FromString,
                    response_serializer=leet__pb2.DecodeResponse.SerializeToString,
            ),
            'EncodeBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.EncodeBatch,
                    request_deserializer=leet__pb2.EncodeRequest.FromString,
                    response_serializer=leet__pb2.EncodeResponse.SerializeToString,
            ),
            'Delta': grpc.unary_unary_rpc_method_handler(
                    servicer.Delta,
                    request_deserializer=leet__pb2.DeltaRequest.FromString,
                    response_serializer=leet__pb2.DeltaResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=leet__pb2.RecallRequest.FromString,
                    response_serializer=leet__pb2.RecallResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=leet__pb2.HealthRequest.FromString,
                    response_serializer=leet__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leet.LeetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('leet.LeetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leet.LeetService/Encode',
            leet__pb2.EncodeRequest.SerializeToString,
            leet__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leet.LeetService/Decode',
            leet__pb2.DecodeRequest.SerializeToString,
            leet__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/leet.LeetService/EncodeBatch',
            leet__pb2.EncodeRequest.SerializeToString,
            leet__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leet.LeetService/Delta',
            leet__pb2.DeltaRequest.SerializeToString,
            leet__pb2.DeltaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leet.LeetService/Recall',
            leet__pb2.RecallRequest.SerializeToString,
            leet__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leet.LeetService/Health',
            leet__pb2.HealthRequest.SerializeToString,
            leet__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
